apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: chat-backend
  template:
    metadata:
      name: backend-pod
      namespace: chat-app
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat-backend
        image: spandan735/chatapp-backend:latest
        ports:
          - containerPort: 5001
        env:
          - name: NODE_ENV
            value: production
          - name: MONGODB_URI
            value: "mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin"
          - name: PORT
            value: "5001"
          - name: JWT_SECRET
            valueFrom: 
              secretKeyRef:
                name: chatapp-secret
                key: jwt
                
