apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: mongo-pv
  resources:
    requests:
      storage: 5Gi